name: deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  install_dependencies:
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: yarn
      - name: Creating node_modules artifact
        uses: actions/upload-artifact@v3
        with:
          name: node_modules-artifact
          path: node_modules


  lint:
    needs: [install_dependencies]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/download-artifact@v3
        with:
          name: node_modules-artifact
          path: node_modules
      - name: Running lint
        run: yarn lint
  
  test:
    needs: [install_dependencies]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/download-artifact@v3
        with:
          name: node_modules-artifact
          path: node_modules
      - name: Running unit test
        run: yarn test

  deployment:
    needs: [lint, test]
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: echo Deployed!!!!!
      