name: deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  unit-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --ignore-engines --ignore-optional
      - name: Running lint
        run: yarn lint
      - name: Running unit test
        run: yarn test
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: echo Deploying!!!!! 
      