name: deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --ignore-engines --ignore-optional --prefer-offline 
      - name: Running lint
        run: yarn lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --ignore-engines --ignore-optional --prefer-offline 
      - name: Running unit test
        run: yarn test

  create-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: home-back:latest


  deployment:
    needs: [lint, test]
    runs-on: self-hosted
    steps:
      - name: deployment
        if: ${{ github.event_name == 'push' }}
        run: echo doploying!
      - uses: actions/checkout@v3
      - name: docker compose
        run: docker compose up -d --build
